name: Front-Prod build & deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: TopazKang
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Docker image
      run: |
        docker build \
        --build-arg DB_NAME=${{ secrets.REACT_APP_SERVER_URL }} \
        -t ghcr.io/topazkang/ddeep-prod-fe:latest .

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/topazkang/ddeep-prod-fe:latest

  deploy:
    runs-on: [ self-hosted, Linux, X64, ddeep-prod-fe ]
    name: Deploy on Self-Hosted Runner
    needs: build

    steps:
      - name: set env & deploy
        run: |
          cd /home/ubuntu/deploy/fe
          docker image prune -a -f
          docker-compose -f docker-compose.front.yaml down
          docker-compose -f docker-compose.front.yaml pull
          docker-compose -f docker-compose.front.yaml up -d